{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: cron
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
    {{- include "cronjob.nameLabels" . | nindent 4 }}
    {{- include "cronjob.appLabels" . | nindent 4 }}
data:
{{- with .Values.configMap.data }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}