{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    {{- include "backend.appLabels" . | nindent 4 }}
    {{- include "backend.nameLabels" . | nindent 4 }}
    {{- include "backend.roleLabels" . | nindent 4 }}
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
